FROM python:3.9-slim

WORKDIR /app

COPY main.py /app/calculadora.py
COPY test_main.py /app/test_calculadora.py

RUN pip install --no-cache-dir unittest

CMD ["python3", "-m", "unittest", "discover", "/app"]