name: Event PR - Single Job

on:
  pull_request:
   labels:
    - "test"

jobs:
  hello_world:
    runs-on: ubuntu-latest
    
    steps:
      - name: First Step 
        run: echo "Hello World!"
      - name: Step 2
        run: echo "Hello Worls 2!"

     
    