name: PR-python

on:
  push:
    branches: 
      - main
    
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run linters
        run: |
          flake8 python

    steps:
      - name: Run security checks
        run: |
          bandit -r python